# Generated by Django 5.1.2 on 2024-10-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
